services:
  db:
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    volumes: []
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "8080:80"
    volumes: []
